[project]
name = "alphagrad"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
    "jax",
    "jaxlib",
    "equinox",
    "optax",
    "distrax",
    "wandb",
    "tqdm",
    "more-itertools",
    "graphax",
    "immutables",
    "grain",
    "tensorflow-datasets",
    "tensorflow",
    "importlib_resources",
    "psutil",
]


#[tool.uv.sources]
#alphagrad = { path = ".", editable = true }
#alphagrad = { workspace = true }
#graphax = { workspace = true }

[build-system]
requires = ["setuptools", "setuptools_scm[toml]"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
# For smarter version schemes and other configuration options,
# check out https://github.com/pypa/setuptools_scm
version_scheme = "no-guess-dev"

[tool.uv.extra-build-dependencies]
flash-attn = ["psutil"]
